import '../model/product.dart';

class MockData {
  static List<Product> getMockProducts() {
    return [
      Product(
        id: '1',
        name: 'Fresh Apples',
        description: 'Crisp, juicy apples perfect for snacking.',
        category: 'Fruits',
        price: 120.0,
        stockQuantity: 50,
        unit: '1kg',
        image:
            'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 30)),
        brand: 'Farm Fresh',
        isOrganic: true,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 52,
          'protein': 0.3,
          'fat': 0.2,
          'carbohydrates': 14,
          'calcium': 6,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Product(
        id: '2',
        name: 'Organic Bananas',
        description: 'Sweet organic bananas, rich in potassium.',
        category: 'Fruits',
        price: 80.0,
        stockQuantity: 30,
        unit: '1 dozen',
        image:
            'https://images.unsplash.com/photo-1574226516831-e1dff420e8f8?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 7)),
        brand: 'Nature\'s Best',
        isOrganic: true,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 89,
          'protein': 1.1,
          'fat': 0.3,
          'carbohydrates': 23,
          'calcium': 5,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Product(
        id: '3',
        name: 'Fresh Tomatoes',
        description: 'Vine-ripened tomatoes, great for salads.',
        category: 'Vegetables',
        price: 60.0,
        stockQuantity: 40,
        unit: '1kg',
        image:
            'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 14)),
        brand: 'Green Valley',
        isOrganic: true,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 18,
          'protein': 0.9,
          'fat': 0.2,
          'carbohydrates': 3.9,
          'calcium': 10,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Product(
        id: '4',
        name: 'Whole Wheat Bread',
        description: 'Soft, healthy whole wheat bread loaf.',
        category: 'Bakery',
        price: 50.0,
        stockQuantity: 25,
        unit: '1 loaf',
        image:
            'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 5)),
        brand: 'Baker\'s Delight',
        isOrganic: false,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 247,
          'protein': 8,
          'fat': 3.4,
          'carbohydrates': 41,
          'calcium': 107,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Product(
        id: '5',
        name: 'Fresh Spinach',
        description: 'Leafy green spinach, packed with nutrients.',
        category: 'Vegetables',
        price: 40.0,
        stockQuantity: 35,
        unit: '500g',
        image:
            'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 10)),
        brand: 'Leafy Greens',
        isOrganic: true,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 23,
          'protein': 2.9,
          'fat': 0.4,
          'carbohydrates': 3.6,
          'calcium': 99,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Product(
        id: '6',
        name: 'Brown Eggs (12 pack)',
        description: 'Farm-fresh brown eggs, dozen pack.',
        category: 'Dairy & Eggs',
        price: 150.0,
        stockQuantity: 20,
        unit: '12 eggs',
        image:
            'https://images.unsplash.com/photo-150674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 21)),
        brand: 'Happy Hens',
        isOrganic: false,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 155,
          'protein': 13,
          'fat': 11,
          'carbohydrates': 1.1,
          'calcium': 50,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
      Product(
        id: '7',
        name: 'Fresh Oranges',
        description: 'Juicy oranges, full of vitamin C.',
        category: 'Fruits',
        price: 100.0,
        stockQuantity: 30,
        unit: '1kg',
        image:
            'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
        expiryDate: DateTime.now().add(const Duration(days: 14)),
        brand: 'Citrus Grove',
        isOrganic: true,
        isAvailable: true,
        nutritionalInfo: {
          'calories': 47,
          'protein': 0.9,
          'fat': 0.1,
          'carbohydrates': 12,
          'calcium': 40,
        },
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      ),
    ];
  }
}
